{% set name = "fhlmi" %}
{% set version = "0.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhlmi-{{ version }}.tar.gz
  sha256: 7750f78c2d6ce2439d4edfa335d1a6fbd4d8a774d9b83588ebdd4c071d3606c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - coredis
    - fhaviary >=0.14.0
    - limits
    - litellm >=1.60.2
    - pydantic >=2.0,<3.dev0,>=2.10.1,<2.10.2
    - tiktoken >=0.4.0

test:
  imports:
    - lmi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Future-House/ldp/tree/main/packages/lmi
  summary: A client to provide LLM responses for FutureHouse applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
