{% set name = "fhlmi" %}
{% set version = "0.45.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhlmi-{{ version }}.tar.gz
  sha256: c81bda4b30d1b6cb874099f000fe5d930c2b40e07d6990fb02a5b8b16140a306

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - aiohttp
    - openai >=2
    - orjson
    - typing_extensions
    - python >={{ python_min }}
    - coredis >=3.0.1
    - fhaviary >=0.14.0
    - limits >=4.8
    - litellm >=1.83.7,<=1.83.10
    - pydantic >=2.0,<3.dev0,>=2.10.1
    - tiktoken >=0.4.0

test:
  imports:
    - lmi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Future-House/ldp/tree/main/packages/lmi
  summary: A client to provide LLM responses for FutureHouse applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
