{% set name = "fhlmi" %}
{% set version = "0.30.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhlmi-{{ version }}.tar.gz
  sha256: 2bba2e39a93b0d222896b141668377d54659adb675cc56a42f2af0a6c67abae6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - coredis
    - fhaviary >=0.14.0
    - limits >=4.8
    - litellm >=1.63.5
    - pydantic >=2.0,<3.dev0,>=2.10.1
    - tiktoken >=0.4.0

test:
  imports:
    - lmi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Future-House/ldp/tree/main/packages/lmi
  summary: A client to provide LLM responses for FutureHouse applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
