{% set name = "fhlmi" %}
{% set version = "0.26.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhlmi-{{ version }}.tar.gz
  sha256: c436a5052d8f8d668ca8df02cb0a24530d298e4999f7af9a8e3f0f10ba244790

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - coredis
    - fhaviary >=0.14.0
    - limits
    - litellm >=1.62.4
    - pydantic >=2.0,<3.dev0,>=2.10.1
    - tiktoken >=0.4.0

test:
  imports:
    - lmi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Future-House/ldp/tree/main/packages/lmi
  summary: A client to provide LLM responses for FutureHouse applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
