schema_version: 1

context:
  name: fhlmi
  version: "0.46.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fhlmi-${{ version }}.tar.gz
  sha256: 56ab14d230bc0b4a48eb880d91f9aad3558d50b4bacb99cc6a52d9e1e6179320

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.11.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - aiohttp
    - openai >=2
    - orjson
    - typing_extensions
    - python >=${{ python_min }}
    - coredis >=3.0.1
    - fhaviary >=0.14.0
    - limits >=4.8
    - litellm >=1.83.9,<=1.83.10
    - pydantic >=2.0,<3.dev0,>=2.10.1
    - tiktoken >=0.4.0

tests:
  - python:
      imports:
        - lmi
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A client to provide LLM responses for FutureHouse applications.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Future-House/ldp/tree/main/packages/lmi

extra:
  recipe-maintainers:
    - jan-janssen
